[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
crowdfunding = "EiU3xntDy5FurzZW8V8DG93m4q2KPsDt4Y1bE7Vt6aNv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "solana/my_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
